/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Mysticreator (https://sketchfab.com/Mysticreator)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/go-gopher-e0e18cb276574666a39d2a0926510fc1
Title: Go Gopher
*/

/*
"Go Gopher" (https://skfb.ly/oGVPE) by Daringcuteseal is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).
*/

import * as THREE from 'three'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { RefObject } from 'react'

type GLTFResult = GLTF & {
  nodes: {
    Object_4: THREE.Mesh
    Object_6: THREE.Mesh
    Object_8: THREE.Mesh
    Object_10: THREE.Mesh
    Object_12: THREE.Mesh
    Object_14: THREE.Mesh
    Object_16: THREE.Mesh
    Object_18: THREE.Mesh
    Object_20: THREE.Mesh
    Object_22: THREE.Mesh
    Object_24: THREE.Mesh
    Object_26: THREE.Mesh
    Object_28: THREE.Mesh
    Object_30: THREE.Mesh
    Object_32: THREE.Mesh
  }
  materials: {
    Material: THREE.MeshStandardMaterial
    ['Material.001']: THREE.MeshStandardMaterial
    ['Material.002']: THREE.MeshStandardMaterial
    ['Material.003']: THREE.MeshStandardMaterial
  }
}

interface Props {
  position: [number, number, number];
  innerRef: RefObject<THREE.Group>;
}

export default function GoGopher({ position, innerRef }: Props) {
  return (
    <group ref={innerRef} position={position} scale={0}>
      <Model />
    </group> 
  );
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/3d-models/go-gopher.glb') as GLTFResult
  return (
    <group {...props} dispose={null} scale={0.4}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Material}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials['Material.001']}
        position={[0.215, 0.276, 0.959]}
        scale={0.321}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Material}
        position={[-0.568, 1.504, -0.069]}
        scale={0.215}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Material}
        position={[0.908, 1.271, -0.095]}
        scale={0.215}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials['Material.002']}
        position={[0.27, 0.558, 1.192]}
        rotation={[-0.013, -0.006, -0.07]}
        scale={0.14}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials['Material.003']}
        position={[0.213, 0.124, 1.032]}
        rotation={[-0.001, 0, -0.049]}
        scale={0.102}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials['Material.003']}
        position={[-0.211, 0.885, 0.958]}
        rotation={[-0.295, -0.285, -0.224]}
        scale={0.381}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials['Material.003']}
        position={[0.746, 0.772, 0.793]}
        rotation={[-0.282, 0.265, -0.036]}
        scale={0.366}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_20.geometry}
        material={materials['Material.002']}
        position={[-0.255, 0.994, 1.355]}
        rotation={[-0.296, -0.009, -0.05]}
        scale={0.109}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_22.geometry}
        material={materials['Material.002']}
        position={[0.788, 0.871, 1.176]}
        rotation={[0.015, -0.07, -0.159]}
        scale={0.109}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_24.geometry}
        material={materials['Material.001']}
        position={[-1.101, -0.189, 0.574]}
        rotation={[0.002, 0.086, 0.399]}
        scale={0.176}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_26.geometry}
        material={materials['Material.001']}
        position={[1.287, -0.597, 0.383]}
        rotation={[-0.204, -0.136, 2.012]}
        scale={0.165}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_28.geometry}
        material={materials['Material.001']}
        position={[-0.69, -1.936, -0.067]}
        rotation={[0.309, -0.722, 1.881]}
        scale={0.176}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_30.geometry}
        material={materials['Material.001']}
        position={[0.207, -1.988, -0.077]}
        rotation={[-0.525, -0.486, 0.575]}
        scale={0.176}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_32.geometry}
        material={materials['Material.001']}
        position={[-0.226, -1.234, -0.991]}
        scale={0.192}
      />
    </group>
  )
}

useGLTF.preload('/3d-models/go-gopher.glb')